### ISSUE TITLE
Memory use is too high?

### ISSUE THREAD

**Issue by hulf025** [timflutre/trimmomatic#5]
Thank you for your good job on trimmomatic, which helps us a lot.
   We now run into some trouble of high Memory use. How do you think about this ?

**Comment by timflutre** [comment]
As explained in the README, I am not the official maintainer of Trimmomatic (I also now prefer to use CutAdapt). For this issue, you should contact Anthony Bolger (http://www.usadellab.org/cms/index.php?page=trimmomatic). Note also that I made this repo with version 0.33 of the code, but A. Bolger may have improved the code since.
