### ISSUE TITLE
HeadCropTrimmer confusion

### ISSUE THREAD

**Issue by lutsik** [timflutre/trimmomatic#6]
Hi,

I wanted to implement something like a "tail-crop trimmer" in trimmomatic terminology, but got a bit confused by the available ones. It seems to me that the actual head-crop trimmer does not do what the documentaiton states. While the manual states:

"HEADCROP: Cut the specified number of bases from the start of the read"

line 22 in HeadCropTrimmer.java

"                return new FastqRecord(in,pos,len-pos);"

implies that the bases are removed from both ends of the read.

Could you please comment on this one?

Best regards,

Pavlo

**Comment by timflutre** [comment]
As explained in the README, I am not the official maintainer of Trimmomatic (I also now prefer to use CutAdapt). For this issue, you should contact Anthony Bolger (http://www.usadellab.org/cms/index.php?page=trimmomatic). Note also that I made this repo with version 0.33 of the code, but A. Bolger may have improved the code since.
Also, if you're interested, I can transfer the ownership of this repo to you.
