### ISSUE TITLE
Generating empty files 

### ISSUE THREAD

**Issue by madzafv** [timflutre/trimmomatic#8]
Hi, 
I'm running the following and getting empty outputs:
java -jar /home/madzays/bin/trimmomatic.jar PE -phred33 /home/madzays/data/finch_data/firstrun/test/RSFV1M_S47_L006_R1_001.fastq /ho me/madzays/data/finch_data/firstrun/test/RSFV1M_S47_L006_R2_001.fastq ./RSFV1M_S47_L006_R1_001_paired.fastq ./RSFV1M_S47_L006_R1_001_unpaired.fastq ./RSFV1M_S47_L006_R2_001_paired.fastq ./RSFV1M_S47_L006_R2_001_unpaired.fastq SLIDINGWINDOW:4:25 MINLEN:36
TrimmomaticPE: Started with arguments: -phred33 /home/madzays/data/finch_data/firstrun/test/RSFV1M_S47_L006_R1_001.fastq /home/madzays/data/finch_data/firstrun/test/RSFV1M_S47_L006_R2_001.fastq ./RSFV1M_S47_L006_R1_001_paired.fastq ./RSFV1M_S47_L006_R1_001_unpaired.fastq ./RSFV1M_S47_L006_R2_001_paired.fastq ./RSFV1M_S47_L006_R2_001_unpaired.fastq SLIDINGWINDOW:4:25 MINLEN:36
Multiple cores found: Using 16 threads
Input Read Pairs: 0 Both Surviving: 0 (�%) Forward Only Surviving: 0 (�%) Reverse Only Surviving: 0 (�%) Dropped: 0 (�%)
TrimmomaticPE: Completed successfully
Any ideas what I might be going wrong?
Thank you!
-madza farias-virgens

**Comment by timflutre** [comment]
As explained in the README, I am not the official maintainer of Trimmomatic (I also now prefer to use CutAdapt). For this issue, you should contact Anthony Bolger (http://www.usadellab.org/cms/index.php?page=trimmomatic). Note also that I made this repo with version 0.33 of the code, but A. Bolger may have improved the code since.
