### ISSUE TITLE
Version 0.36 uses only one thread

### ISSUE THREAD

**Issue by patrick-douglas** [timflutre/trimmomatic#9]
I'm running Trimmomatic 0.36 in a machine with 12 cores, but the program uses only one core.
See my command line below: 
`java -jar trimmomatic-0.36.jar SE -phred64 todos_um.fastq todos_um_phred05.fastq SLIDINGWINDOW:4:15 LEADING:3 TRAILING:3 MINLEN:36 -threads 12 -trimlog trimLogFile.txt `

**Comment by timflutre** [comment]
As explained in the README, I am not the official maintainer of Trimmomatic (I also now prefer to use CutAdapt). For this issue, you should contact Anthony Bolger (http://www.usadellab.org/cms/index.php?page=trimmomatic). Note also that I made this repo with version 0.33 of the code, but A. Bolger may have improved the code since.
